- name: create a rabbitmq container
  # docker_container:
  community.general.docker_container:
    name: '{{ rabbitmq_container_name }}'
    image: '{{ rabbitmq_image_name }}'
    pull: '{{ docker_pull }}'
    state: started
    recreate: yes
    exposed_ports: '{{ rabbitmq_exposed_ports }}'
    published_ports: '{{ rabbitmq_published_ports }}'
    env: '{{ rabbitmq_environment }}'
    volumes: '{{ rabbitmq_volumes }}'

    log_driver: '{{ rabbitmq_log_driver }}'
    log_options: '{{ rabbitmq_log_options }}'

    network_mode: '{{ rabbitmq_network_mode }}'
    etc_hosts: '{{ rabbitmq_etc_hosts }}'

    restart_policy: always
    container_default_behavior: '{{ rabbitmq_default_behavior }}'
  register: rabbitmq_docker_installed
  tags:
    - rabbitmq_container

- block:
  - name: wait until RabbitMQ stands up
    wait_for:
      host: '127.0.0.1'
      port: '{{ rabbitmq_port }}'
      delay: 2

  become: yes
