- name: ensure necessary PostgreSQL users are present
  become: true
  become_user: postgres
  postgresql_user:
    name: '{{ item.name }}'
    password: '{{ item.password }}'
    # encrypted: true
    # login_unix_socket: "{{ postgresql_unix_socket_dir }}"
    port: '{{ postgres_port }}'
    role_attr_flags: '{{ item.privs }}'
    state: present
  # ignore_errors: true
  loop: '{{ postgres_users }}'
  loop_control:
    label: '{{ item.name }}'
  when: 'postgres_users is defined and postgres_users | length > 0'
  tags:
    - postgres_users
