---
- name: restart nginx docker
  docker_container:
    name: '{{ nginx_container_name }}'
    # image: '{{ nginx_image_name }}'
    state: started
    restart: yes
    trust_image_content: yes
  listen: 'restart nginx_docker'

- name: reload nginx docker
  command: docker kill -s HUP {{ nginx_container_name }}
  listen: 'reload nginx_docker'
