---
- name: Start disable-transparent-huge-pages service
  become: true
  systemd:
    daemon_reload: true
    name: disable-transparent-huge-pages
    state: restarted
    enabled: true
  listen: 'restart disable-thp'
