- name: ensure settings is up to date
  become: yes
  template:
    src: cluster.py.j2
    dest: '{{ sites_home }}/{{ settings_module_name }}.py'
    owner: '{{ pp_uid }}'
    group: '{{ pp_gid }}'
    mode: '0440'
  tags:
    - pp_conf

- name: log into PricePlan registry
  docker_login:
    registry: registry.priceplan.pro
    username: '{{ registry_user }}'
    password: '{{ registry_password }}'
    # reauthorize: yes

- name: run bunch of PricePlan services...
  vars:
    taget_container_desc: '{{ pp_layout[item].desc }}'
    taget_container_name: '{{ pp_layout[item].name }}'
    target_commnad: '{{ pp_layout[item].command }}'
    target_group: '{{ item }}'
  include_tasks: start.yaml
  loop: '{{ pp_layout.keys() | list }}'

- name: Log out of PricePlan registry
  docker_login:
    registry: registry.priceplan.pro
    state: absent
