- name: ensure settings is up to date
  become: yes
  template:
    src: cluster.py.j2
    dest: '{{ sites_home }}/{{ settings_module_name }}.py'
    owner: '{{ pp_uid }}'
    group: '{{ pp_gid }}'
    mode: '0440'
  tags:
    - pp_conf

- name: log into PricePlan registry
  docker_login:
    registry: '{{ docker_registry }}'
    username: '{{ registry_user }}'
    password: '{{ registry_password }}'
    # reauthorize: yes
  tags:
    - registry_login

- name: run migrations
  docker_container:
    name: pp_migrations
    image: '{{ pp_image_name }}'
    pull: '{{ docker_pull }}'
    # state: started
    recreate: yes
    detach: no
    interactive: yes
    tty: yes
    # auto_remove: yes

    log_driver: '{{ pp_log_driver }}'
    log_options: '{{ pp_log_options }}'
    network_mode: '{{ pp_network_mode }}'

    exposed_ports: []
    published_ports: []
    env: '{{ pp_environment }}'
    links: '{{ pp_links }}'
    volumes: '{{ pp_volumes | default([]) }}'
    restart_policy: 'no'
    command: 'mng migrate_schema --schema=main'
    container_default_behavior: '{{ pp_default_behavior }}'

  when:
    inventory_hostname == groups.pp_cluster[0]
  register: migration_applied
  tags:
    - migrations

- name: echo migration output
  debug:
    var: migration_applied.ansible_facts.docker_container.Output
  when:
    inventory_hostname == groups.pp_cluster[0]
  tags:
    - migrations

- name: run bunch of PricePlan services...
  vars:
    taget_container_desc: '{{ pp_layout[item].desc }}'
    taget_container_name: '{{ pp_layout[item].name }}'
    target_commnad: '{{ pp_layout[item].command }}'
    target_group: '{{ item }}'
  include_tasks: start.yaml
  loop: '{{ pp_layout.keys() | list }}'

- name: Log out of PricePlan registry
  docker_login:
    registry: '{{ docker_registry }}'
    state: absent
  tags:
    - registry_logout
