- name: run {{ taget_container_desc }}
  docker_container:
    name: '{{ taget_container_name }}'
    image: '{{ pp_image_name }}'
    # pull: '{{ docker_pull }}'
    state: started
    recreate: yes

    log_driver: '{{ pp_log_driver }}'
    log_options: '{{ pp_log_options }}'
    network_mode: '{{ pp_network_mode }}'

    exposed_ports: []
    published_ports: []
    env: '{{ pp_environment }}'
    links: '{{ pp_links }}'
    volumes: '{{ target_volumes | default([]) }}'
    restart_policy: always
    command: '{{ target_commnad }}'
    container_default_behavior: '{{ pp_default_behavior }}'
  when: target_group in group_names
