pp_image_name: 'registry.priceplan.pro/priceplan/priceplan:{{ pp_image_version }}'

pp_uwsgi_container_name: pp_uwsgi
pp_common_container_name: pp_common
pp_billing_container_name: pp_billing
pp_ordinal_container_name: pp_ordinal
pp_mail_container_name: pp_mail
pp_http_container_name: pp_http
pp_search_container_name: pp_search
pp_cron_container_name: pp_cron
pp_flower_container_name: pp_flower

pp_network_mode: host
pp_log_driver: json-file
pp_log_options:
  mode: non-blocking
  max-buffer-size: 4m

pp_links: []
pp_volumes:
  - '{{ sites_home }}/{{ settings_module_name }}.py:/pp/priceplan/settings/{{ settings_module_name }}.py:ro'

pp_environment:
  SECRET_KEY: '{{ pp_secret_key }}'
  DJANGO_SETTINGS_MODULE: 'priceplan.settings.{{ settings_module_name }}'
  PRICEPLAN_LOGSTASH_HOST: 127.0.0.1
  # PRICEPLAN_PG_DATABASE:
  # PRICEPLAN_PG_USER:
  # PRICEPLAN_PG_PASSWORD:
  # PRICEPLAN_PG_HOST:
  # PRICEPLAN_PG_PORT:

pp_uid: '122'
pp_gid: '998'
