pp_image_name: 'priceplan/priceplan:{{ pp_image_version }}'

pp_network_mode: host
pp_log_driver: json-file
pp_log_options:
  mode: non-blocking
  max-buffer-size: 4m

pp_links: []
pp_volumes:
  - '{{ sites_home }}/{{ settings_module_name }}.py:/pp/priceplan/settings/{{ settings_module_name }}.py:ro'

pp_environment:
  SECRET_KEY: '{{ pp_secret_key }}'
  DJANGO_SETTINGS_MODULE: 'priceplan.settings.{{ settings_module_name }}'
  PRICEPLAN_LOGSTASH_HOST: 127.0.0.1

pp_uid: '122'
pp_gid: '998'

pp_default_behavior: '{{ docker_default_behavior | default("no_defaults") }}'

pp_layout:
  uwsgi:
    name: pp_wsgi
    desc: WSGI server
    command:
    - wsgi
  common:
    name: pp_common
    desc: worker for common tasks
    command:
    - common
  billing:
    name: pp_billing
    desc: worker for billing tasks
    command:
    - billing
  ordinal:
    name: pp_ordinal
    desc: worker for client level billing tasks
    command:
    - ordinal
  mail:
    name: pp_mail
    desc: worker for send mail tasks
    command:
    - mail
  http:
    name: pp_http
    desc: worker for http hooks
    command:
    - http
  search:
    name: pp_search
    desc: worker for search tasks
    command:
    - search
  cron:
    name: pp_cron
    desc: cron worker
    command:
    - master
  flower:
    name: pp_flower
    desc: flower
    command:
    - flower
