# tasks file for postgres
---
- name: start to ensure postgres installed
  include_tasks: centos-8.yaml
  when: ansible_distribution == 'CentOS' and
        ansible_distribution_major_version == '8'
  tags:
    - postgres
