# Deploy whole stack of PricePlan
---
- name: Deploy PricePlan on cluster
  hosts:
    - pp_cluster
    - load_balancer
  # strategy: debug
  gather_facts: yes

  roles:
    - role: transparent_huge_pages
      tags:
      - disable_thp
      - base

    - role: timezone
      tags:
      - timezone
      - base

    - role: locales
      tags:
      - locales
      - base

    - role: ntp
      tags:
      - ntp
      - base

    - role: docker
      when: '"pp_cluster" in group_names'
      tags:
      - docker
      - base

    - role: 'dockers/etcd'
      when: '"etcd_cluster" in group_names'
      tags:
      - etcd
      - pg

    - role: postgresql
      when: '"postgres_cluster" in group_names'
      tags:
      - postgres
      - pg

    - role: patroni
      when: '"postgres_cluster" in group_names'
      tags:
      - patroni
      - pg

    - role: postgresql-users
      when: '"master" in group_names and postgres_users | length > 0'
      tags:
      - postgres_users
      - pg

    - role: postgresql-databases
      when: '"master" in group_names and postgres_users | length > 0'
      tags:
      - postgres_dbs
      - pg

    # - role: pgbouncer
    #   when: '"postgres_cluster" in group_names'
    #   tags:
    #   - pgbouncer

    - role: 'dockers/redis'
      when: '"redis_cluster" in group_names'
      tags:
      - redis

    - role: haproxy
      when: '"pp_cluster" in group_names or "load_balancer" in group_names'
      tags:
      - haproxy


    - role: 'dockers/rabbitmq'
      when: '"rabbitmq_cluster" in group_names'
      tags:
      - rabbitmq

    - role: 'dockers/nginx'
      when: '"nginx" in group_names'
      tags:
      - nginx-server
      - elk

    - role: 'dockers/elasticsearch'
      when: '"elasticsearch_cluster" in group_names'
      tags:
      - elastic
      - elk

    - role: 'dockers/logstash'
      when: '"logstash" in group_names'
      tags:
      - logstash
      - elk

    - role: 'dockers/kibana'
      when: '"kibana" in group_names'
      tags:
      - kibana
      - elk

    - role: assist/webfront-kibana
      when: '"webfront" in group_names'
      tags:
      - kibana
      - kibana_front
      - elk

    - role: priceplan
      when: '"pp_cluster" in group_names'
      tags:
      - pp

    - role: assist/webfront-priceplan
      when: '"webfront" in group_names'
      tags:
      - pp
      - webfront
