# Deploy whole stack of PricePlan
---
- name: Deploy PricePlan on cluster
  hosts:
    - pp_cluster
  # strategy: debug
  gather_facts: yes

  roles:
    - role: transparent_huge_pages
      tags:
      - disable_thp

    - role: timezone
      tags:
      - timezone

    - role: locales
      tags:
      - locales

    - role: ntp
      tags:
      - ntp

    - role: docker
      when: '"pp_cluster" in group_names'
      tags:
      - docker

    - role: 'dockers/etcd'
      when: '"etcd_cluster" in group_names'
      tags:
      - etcd
      - etcd_conf

    - role: postgresql
      when: '"postgres_cluster" in group_names'
      tags:
      - postgres

    - role: patroni
      when: '"postgres_cluster" in group_names'
      tags:
      - patroni

    - role: postgresql-users
      when: '"master" in group_names and postgres_users | length > 0'
      tags:
      - postgres_users

    - role: postgresql-databases
      when: '"master" in group_names and postgres_users | length > 0'
      tags:
      - postgres_dbs

    - role: pgbouncer
      when: '"postgres_cluster" in group_names'
      tags:
      - pgbouncer

    - role: haproxy
      when: '"postgres_cluster" in group_names'
      tags:
      - haproxy

    - role: 'dockers/redis'
      when: '"redis_cluster" in group_names'
      tags:
      - redis
